# Usa l'immagine ufficiale di MySQL
FROM mysql:latest

# Imposta variabili d'ambiente (minime necessarie)
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Espone la porta
EXPOSE 3306